name = "VpinEstimation"
uuid = "98b75bef-cec7-42fd-9fd8-1608d125fef6"
authors = ["fanjinyun"]
version = "0.1.0"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
julia = "1.6.7"
CSV = "0.10.0, 0.10.14"
DataFrames = "1.7.0"
Distributions = "0.25.0, 0.25.112"
ProgressMeter = "1.10.0, 1.10.2"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
